### ISSUE TITLE
cannot compile with cmake on ubuntu 14.04

### ISSUE THREAD

**Issue by AllenZzw** [toulbar2/toulbar2#2]
I try to install toulbar2 in ubuntu 14.04 on a 32 bit machine, but I found the following error when I tried to "make package": 

/usr/bin/ld: cannot find -lBoost::iostreams
collect2: error: ld returned 1 exit status
make[2]: *** [bin/Linux/toulbar2] Error 1
make[2]: Leaving directory `/home/ubuntu/toulbar2/build'
make[1]: *** [CMakeFiles/toulbar2.dir/all] Error 2
make[1]: Leaving directory `/home/ubuntu/toulbar2/build'
make: *** [all] Error 2

it seems like I cannot link the boost library. Can anyone help on this?

**Comment by tschiex** [comment]
Hello Allen

You are the second one to report this this week. I haven't looked into
it deeply yet, but the previous person solved this using a more recent
cmake version (3.20 I think). It seems that old cmake versions have
problems with boost and generate improper linking directives (you would
need a -lboost_iostreams or a
/usr/lib/x86_64-linux-gnu/libboost_iostreams.so in the final linking
command instead of -lBoost::iostreams).

For the moment I would advise to either edit and run the final linking
command in the shell from the build directory (replacing
-lBoost::iostreams by -lboost_iostreams) or to install a more recent cmake.

We will be looking into this.

Thomas


Le 09/08/2018 à 08:53, Allen a écrit :

**Comment by AllenZzw** [comment]
Thank you! Your suggestion is very helpful! I tried replacing -lBoost::iostreams by -lboost_iostreams, and it worked! 

I also tried to install cmake 3.2.2. When compiling, I got the following message: 

> CMake Warning (dev) at CMakeLists.txt:297 (add_executable):
>   Policy CMP0028 is not set: Double colon in target name means ALIAS or
>   IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
>   Use the cmake_policy command to set the policy and suppress this warning.
> 
>   Target "toulbar2" links to target "Boost::iostreams" but the target was not
>   found.  Perhaps a find_package() call is missing for an IMPORTED target, or
>   an ALIAS target is missing?
> This warning is for project developers.  Use -Wno-dev to suppress it.

and still, I got the same error when I tried "make package". Hope that this message will be helpful for your investigation.  

Allen

**Comment by tschiex** [comment]
I just pushed what looks like a fix to me.

If you could test from a fresh clone, that would be great :-)

Thomas



Le 09/08/2018 à 10:19, Allen a écrit :

**Comment by AllenZzw** [comment]
Yes, the fix works! Thank you!
